services:
  - type: web
    name: sliding-window-api
    env: python
    region: singapore
    plan: free
    pythonVersion: "3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true